// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type CreateUserInput struct {
	Username  string  `json:"username"`
	Password  string  `json:"password"`
	FirstName string  `json:"firstName"`
	LastName  string  `json:"lastName"`
	Age       *int    `json:"age,omitempty"`
	Birthday  *string `json:"birthday,omitempty"`
}

type UpdateUserInput struct {
	Username  string  `json:"username"`
	Password  string  `json:"password"`
	FirstName string  `json:"firstName"`
	LastName  string  `json:"lastName"`
	Age       *int    `json:"age,omitempty"`
	Birthday  *string `json:"birthday,omitempty"`
}

type User struct {
	ID        string  `json:"id"`
	Username  string  `json:"username"`
	Password  string  `json:"password"`
	FirstName string  `json:"firstName"`
	LastName  string  `json:"lastName"`
	Age       *int    `json:"age,omitempty"`
	Birthday  *string `json:"birthday,omitempty"`
}
